apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::334088250692:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1CS70VZ2HYRWZ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::arn:aws:iam::334088250692:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-29T19:40:25Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1783"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 68fda27c-efeb-414f-aa52-c0d15b66ed05
