apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::334088250692:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-8X1XJ1T7KJ0R
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::334088250692:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-30T16:37:09Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1582"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: c82cf76f-de05-4c37-8d47-027c3374e346
